services:
  - type: web
    name: websocket-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
    runtime: docker
